### ISSUE TITLE
Create a recipe to manage gems from an attribute

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/pantry#10]
This will be for gems that are required by the user with ChefDK. For example I like the `git-up` gem and want it installed on my workstation. 

This has special considerations:
1. Installing using `chef gem install`
2. Installing using the non-privileged user so that gems are in their home directory

This may end up being a new resource that gets used or something magical with gem_package.

**Comment by josegonzalez** [comment]
Would you want these gems installed in the chef-dk gem path, global ruby, or a custom one via rbenv?

**Comment by jtimberman** [comment]
ChefDK. It's the only ruby end reliably on the system with this and I don't want to extend this to support various ruby managers. Folks can add that to their run list. 

Main consideration is this needs to install as the user in their ~/.chefdk instead of roots.

**Comment by tas50** [comment]
Closing as we've deprecated this cookbook
