### ISSUE TITLE
Consider how this fits in with Policyfiles

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/pantry#15]
With Policyfiles, it's possible that much functionality in this cookbook is unnecessary. For example, the following policyfile can replicate much functionality that this cookbook provides on OS X:

``` ruby
name "pantry"
default_source :community

run_list ["homebrew", "homebrew::cask", "homebrew::install_taps", "homebrew::install_formulas", "homebrew::install_casks"]

default["homebrew"].tap do |homebrew|
  homebrew["casks"] = ["steam", "github", "atom", "google-chrome"]
  homebrew["formulas"] = ["openvpn", "w3m", "emacs"]
end
```

**Comment by jtimberman** [comment]
Similarly, a policyfile that would work on Debian Linux:

```ruby
name "pantry"
run_list ["packages"]

default["packages"] = ["emacs", "vim", "zsh"]
```

(It would probably also work on RHEL-family given that those packages are also available)

**Comment by jtimberman** [comment]
Note that in these examples, this cookbook is not needed at all.

**Comment by tas50** [comment]
Closing as we've deprecated this cookbook
