### ISSUE TITLE
package manager scaffolding

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/pantry#5]
We should be able to do cross platform package installation from an array of package names.

Homebrew cookbook does this with formulas and casks.

Packages cookbook does this with native packages.

Chocolatey cookbook doesn't have a recipe for this, but it could, or we could just have `pantry::windows` do it.

**Comment by jtimberman** [comment]
I wrote a quick gist about whether there should be a new attribute namespace for pantry, but I don't think that will be a thing.

https://gist.github.com/jtimberman/60fe7ed10737fd64536c

**Comment by patcon** [comment]
Mind if I add support for debian as part of this issue? Setting up a new server workstation, so seems like a good time

**Comment by tas50** [comment]
Closing as we've deprecated this cookbook
