### ISSUE TITLE
Create a recipe to manage repositories from an attribute

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/pantry#6]
The idea is, you set a few attributes. First, a user:

```ruby
default['pantry']['user'] = 'jtimberman'
```

We want the option of specifying the "pantry" user. We assume only a single user because this cookbook is for a workstation, and we've established that workstations are personal things, and not commonly shared amongst people. Maybe someday we'll have a "pantry-multiuser" but that's much further down the road.

Pantry must be run as root per the `pantry` script, which exits with an error if it's not run as root, and per the requirement of many things we will want to manage or that users may want to manage. This attribute can be set anywhere, and we will probably attempt to find the user in a similar manner to how the homebrew user is detected. In fact, we may just reuse that module since it's available and will do the most likely thing we want.

Then, set an attribute for the repositories.

```ruby
default['pantry']['repositories'] = [
  {
    'source' => 'https://github.com/opscode-cookbooks/pantry.git',
    'destination' => '~/src/cookbooks/pantry'
  }
]
# OR!
default['pantry']['repositories'] = {
  'pantry-cookbook' => {
    'source' => 'https://github.com/opscode-cookbooks/pantry.git',
    'destination' => '~/src/cookbooks/pantry'
  }
}
```

I'm leaning toward the second syntax, as it makes it easier to reason about from a data manipulation standpoint, and we are less likely to run into [awkward array merging](https://coderanger.net/arrays-and-chef/).

This should be an empty set by default, because we aren't going to make assumptions about the repositories that users want. We also won't attempt to update repositories, we're only going to check them out (clone). Perhaps in the future we can attempt to update all clean repositories that are on the default tracking branch, but that would be for another time.

**Comment by josegonzalez** [comment]
@jtimberman If you can point out how the homebrew user is detected (I've poked around and copying their attempts seem to fail for me with the mixin provided) I'd be happy to take a stab at this. I currently have a simple recipe that does this, though I hardcoded my user for now.

**Comment by jtimberman** [comment]
Heres a starter. http://jtimberman.housepub.org/blog/2014/12/29/chef-12-homebrew-user-mixin/

**Comment by josegonzalez** [comment]
I have the following bit of code, but I don't think it'd work on Windows (or Linux due to the mixin usage):

```ruby
::Chef::Resource.send(:include, ::Homebrew::Mixin)
::Chef::Recipe.send(:include, Chef::Mixin::ShellOut)

username = shell_out('whoami', :user => Chef12HomebrewUser.new.find_homebrew_uid).stdout.split("\n")[0]

node['pantry']['repositories'].each do |name, config|
  home_dir = ENV['HOME']
  ENV['HOME'] = Dir.home(username)
  destination = ::File.expand_path(config['destination'])
  ENV['HOME'] = home_dir

  git destination do
    action :checkout
    group 'staff'
    repository config['source']
    revision config.fetch('revision', 'master')
    user username
  end
end
```

Thoughts on how to change it for windows support?

**Comment by josegonzalez** [comment]
I updated the PR to take care of the case where the git resource creates a `deploy` branch (something that doesn't seem overridable).

**Comment by jtimberman** [comment]
There is a resource property for that, `checkout_branch`. 

checkout_branch	Use to specify the name of a branch to be checked out. Default value: deploy.

http://docs.chef.io/resource_git.html

**Comment by josegonzalez** [comment]
This is the issue I am tracking that blocks what i would have otherwise thought would work: https://github.com/chef/chef/issues/1984
